/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.uci.ics.junyanj1.simple_server;

import org.junit.Test;
import static org.junit.Assert.*;

public class SimpleServerTest {
    @Test public void testAppHasAGreeting() {
        SimpleServer classUnderTest = new SimpleServer();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
