/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.uci.ics.junyanj1.simple_server;

public class SimpleServer {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new SimpleServer().getGreeting());
    }
}
